<template>
  <bk-popover
    always
    boundary="#oooxxxvvv"
    placement="right"
    width="300"
    content="这里是提示文字当鼠标经过这段文字时，会显示一个气泡框当鼠标经过这段文字时，会显示一个气泡框当鼠标经过这段文字时"
  >
    <bk-button>总是显示</bk-button>
  </bk-popover>
</template>
