<template>
  <div>
    <bk-input
      class="mb10"
      size="small"
    />
    <bk-input
      size="small"
      class="mb10"
      type="url"
      prefix="https://"
    />
    <bk-input class="mb10" />
    <bk-input
      class="mb10"
      type="url"
      suffix="@qq.com"
    />
    <bk-input
      size="large"
      class="mb10"
      type="search"
    />
    <bk-input
      class="mb10"
      size="large"
    />
  </div>
</template>
