declare interface Window {
  SITE_URL: string;
  vue: Function;
  lodash: Function;
  uuid: Function;
  popperjsCore: Function;
  vueTypes: Function;
  lodashThrottle: Function;
  lodashMerge: Function;
  getComponent: Function;
  lodashIsElement: Function;
  lodashRandom: Function;
  lodashCloneDeep: Function;
  lodashDebounce: Function;
  lodashIsFunction: Function;
  lodashGet: Function;
  lodashIsDate: Function;
  lodashIsEmpty: Function;
  lodashIsEqual: Function;
  lodashIsNumber: Function;
  lodashTrim: Function;
  lodashHas: Function;
  normalizeWheel: Function;
  floatingUiDom: Function;
  floatingUiVue: Function;
  forkResizeDetector: Function;
  dateFns: Function;
  jsCalendar: Function;
  resizeObserverPolyfill: Function;
  clipboard: Function;
  jsonFormatterJs: Function;
  tinycolor2: Function;
  dompurify: Function;
  sparkMd5: Function;
  diff: Function;
  diff2html: Function;
  _code_diff_src_diff2html_bundles_css_diff2html_min_css: Function;
}

declare module 'uuid';
declare module 'normalize-wheel';
declare module 'js-calendar';
declare module 'markdown-it';
declare module '@blueking/xss-filter';
declare module 'markdown-it-task-lists';
declare module 'tinycolor2';
declare module 'markdown-it-container';
declare module 'dompurify';
declare module 'spark-md5';
declare module 'diff';
declare module 'diff2html';
declare module 'diff2html/bundles/css/diff2html.min.css';

declare module '*.md';
